/* config.h - generated by the 'configure' script */
#ifndef CONFIG_H
#define CONFIG_H 1

#define ARCH ppc64
#define RISU_MACOS9
#define NO_SIGNAL
#define __STDC_FORMAT_MACROS
#define SKIP_GETENV
#define __STDC__ 1
#define SIGBUS 8
#define SIGUNKNOWN 9
#endif /* CONFIG_H */
